# Butterfly 主题配置文件
# 文档: https://butterfly.js.org/

# 导航栏设置
nav:
  logo: # 网站的 logo，支持图片，直接填入图片链接
  display_title: true
  fixed: false # 固定导航栏

# 菜单设置
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  分类: /categories/ || fas fa-folder-open
  标签: /tags/ || fas fa-tags
  关于: /about/ || fas fa-heart

# 代码块设置
code_blocks:
  theme: light # light | dark | mac | mac light
  macStyle: true
  height_limit: false # 代码块展开限制高度
  word_wrap: false

# 社交链接
social:
  fab fa-github: https://github.com/VVVVVenxo || Github
  fas fa-envelope: mailto:1263147353@qq.com || Email
  fab fa-steam: https://steamcommunity.com/profiles/76561198863443106/ || Steam

# 头像设置
avatar:
  img: https://lh3.googleusercontent.com/a/ACg8ocIQldXs-nudxFVZahP5o7kbC5wBEuOI68oSn3XnRW2LA47asB8=s96-c
  effect: false # 头像旋转效果

# 首页文章卡片设置
index_card_style: card # card | full_card

# 文章顶部封面
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both # left | right | both
  default_cover: # 默认封面，可以是数组

# 文章页设置
post_meta:
  page:
    date_type: both # created / updated / both
    date_format: relative # date/relative
    categories: true
    tags: true
    label: true
  post:
    date_type: both
    date_format: relative
    categories: true
    tags: true
    label: true

# 文章版权
post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 目录 TOC
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right # left | right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: To be a rock and not to roll.
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/VVVVVenxo
  card_announcement:
    enable: false
    content:
  card_recent_post:
    enable: true
    limit: 5
    sort: date # date | updated
    sort_order: # 留空为降序
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order:
  card_tags:
    enable: true
    limit: 40
    color: false
    orderby: random
    order: 1
    sort_order:
  card_archives:
    enable: true
    type: monthly # monthly | yearly
    format: MMMM YYYY
    order: -1
    limit: 8
    sort_order:
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:

# 页脚设置
footer:
  owner:
    enable: true
    since: 2024
  custom_text: Everything's Alright
  copyright: true

# 右下角按钮
rightside_bottom: 

# 返回顶部按钮
go_up:
  enable: true

# 暗色模式
darkmode:
  enable: true
  button: true
  autoChangeMode: false # 1: 跟随系统 2: 根据时间自动切换

# 阅读模式
readmode: true

# 复制设置
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

# 搜索设置 - 使用本地搜索
local_search:
  enable: true
  preload: false
  CDN:

# 数学公式
math:
  enable: false
  per_page: true

# 图片懒加载
lazyload:
  enable: true
  field: site # site | post
  placeholder:
  blur: false

# 图片查看器
# 使用 fancybox
fancybox: true

# 页面加载动画
preloader:
  enable: false
  source: 1 # 1: 全屏 2: pace.js
  pace_css_url:

# 字数统计
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# 不蒜子统计
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 打字机效果
subtitle:
  enable: false
  effect: true
  loop: true
  source: false
  sub:

# 页面锚点
anchor:
  auto_update: false
  click:
    enable: false
    always_show: false

# 图片大图查看模式
photofigcaption: false

# Open Graph 设置
Open_Graph_meta:
  enable: true
  option:

# 页面美化
beautify:
  enable: true
  field: post # site | post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: '#F47466'

# 字体设置
font:
  global-font-size:
  code-font-size:
  font-family:
  code-font-family:

# 网站背景
background:

# 页脚背景
footer_bg: false

# 主题色
theme_color:
  enable: false
  main: '#49B1F5'
  paginator: '#00c4b6'
  button_hover: '#FF7242'
  text_selection: '#00c4b6'
  link_color: '#99a9bf'
  meta_color: '#858585'
  hr_color: '#A4D8FA'
  code_foreground: '#F47466'
  code_background: 'rgba(27,31,35,.05)'
  toc_color: '#00c4b6'
  blockquote_padding_color: '#49b1f5'
  blockquote_background_color: '#49b1f5'
  scrollbar_color: '#49b1f5'

# 分类页和标签页 UI
category_ui:
tag_ui:

# 页面过渡效果
pjax:
  enable: false

# Inject - 插入代码到头部或底部
inject:
  head:
  bottom:

# CDN 设置
CDN:
  third_party_provider: local # local | jsdelivr | cdnjs | unpkg | custom
  option:
